### PR TITLE
adding support for stc15f208ea and stc15w408as mcus

### PR DESCRIPTION
**Pull request by zerog2k**
* adds support for some stc mcus
* adds support for the stcgal uploader tool (https://github.com/grigorig/stcgal)
* updates links to new platformio org home

@Palatis & @ivankravets  please review

### CODE REVIEW

**Comment by Palatis** [comment]
can I kindly ask you to:
1. add a platformio package for stcgal so it automatically find + download + install the required tools?
2. split Palatis => platformio to another merge request? I know this is a bit annoying, but that keeps the merge history clean.

**Comment by zerog2k** [comment]
@Palatis ok, maybe you can help me understand the options for item 1.
Stcgal is provided as python3 repo at the moment. Currently, I'm including this as a submodule in my existing project repos (and referencing it directly with my older makefile patterns.) 
I'm not sure what the best way to "package" this w/ platformio in some crossplatform way. Could it be a simple submodule repo of the platform-mcs51, or should it be in a separate tools repo? (I'm just getting my head around the platformio stuff ;)

**Comment by ivankravets** [comment]
@zerog2k 

> maybe you can help me understand the options for item 1.
> Stcgal is provided as python3 repo at the moment. 

I'll add it, I saw it in your repo :)

**Comment by zerog2k** [comment]
ok thanks @Palatis @ivankravets i have tried rebasing to master and updating... hope i didnt mangle it up too much.. (Not sure if you guys just do squash merge anyhow)

**Comment by zerog2k** [comment]
Thanks @ivankravets 
I'm not sure if i mentioned it - the stcgal repo is at https://github.com/grigorig/stcgal

**Comment by Palatis** [comment]
we should also update the README file to point out that we support more boards now :-D

**Comment by zerog2k** [comment]
@Palatis updated readme and added one more stc mcu

**Pull request merged**
