### PR TITLE
set board upload required fields

### PR DESCRIPTION
**Pull request by zerog2k**
fixes float error in #8

### CODE REVIEW

**Comment by ivankravets** [comment]
Thank you so much! Need to finally release this dev/platform. Will add it to TODO.

**Comment by zerog2k** [comment]
Thanks, still learning platformio platforms/frameworks/etc lifecycle... Please let me know if you see anything here which needs improvement.

**Comment by ivankravets** [comment]
Each board here https://github.com/platformio/platform-mcs51/tree/master/boards should have valid `url` field which should lead to vendor/page site. Could you help with this?

**Comment by ivankravets** [comment]
For example, https://github.com/platformio/platform-mcs51/blob/master/boards/n79e8432.json#L23 , should be `http://www.nuvoton.com/hq/products/microcontrollers/8bit-8051-mcus/low-pin-count-8051-series/n79e8432/`

**Pull request merged**
